"""Plagiarism & AI-likelihood analysis service.

This module wraps two LLM providers — OpenAI and Google Gemini — behind a
small functional API used by the ``/api/plagiarism`` routes. The two
providers are interchangeable per call: callers pick "openai", "gemini",
or "auto" (try OpenAI first, fall back to Gemini).

Important honesty note
----------------------
Pure-LLM "plagiarism detection" cannot search the web or compare against
a copyrighted corpus. What this service actually does is:

  * Score how *AI-generated-sounding* the text reads (prompt patterns,
    boilerplate phrases, generic transitions).
  * Score how *unoriginal/templated* the prose looks against common
    academic clichés.
  * Flag specific passages and propose rewrites.

The combined "overall_score" is a heuristic the model returns. We surface
it transparently in the UI rather than pretending it's an authoritative
match against a database.
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, Literal, Optional

from app.core.logging import get_logger

log = get_logger(__name__)


# ---------------------------------------------------------------------------
# Lazy-initialised SDK clients
# ---------------------------------------------------------------------------

_openai_client = None  # type: ignore[var-annotated]
_gemini_client = None  # type: ignore[var-annotated]


def _get_openai():
    """Return a memoised OpenAI client. Raises if OPENAI_API_KEY missing."""
    global _openai_client
    if _openai_client is None:
        from openai import OpenAI  # local import keeps module load fast

        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            raise RuntimeError("OPENAI_API_KEY is not configured")
        _openai_client = OpenAI(api_key=api_key)
    return _openai_client


def _get_gemini():
    """Return a memoised google-genai client. Raises if GEMINI_API_KEY missing."""
    global _gemini_client
    if _gemini_client is None:
        from google import genai  # local import; package is heavy

        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            raise RuntimeError("GEMINI_API_KEY is not configured")
        _gemini_client = genai.Client(api_key=api_key)
    return _gemini_client


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

CHECK_SYSTEM_PROMPT = """You are an experienced academic-writing originality
analyst. Given a passage of text, you assess two things:

1) ORIGINALITY: how much of the writing reads as templated, boilerplate, or
   commonly-recycled academic phrasing (NOT a database match — a heuristic
   based on language patterns).
2) AI-LIKELIHOOD: how much the writing reads as machine-generated by a
   modern LLM (cadence, transitions, hedging language, generic phrasing).

You MUST respond with a strict JSON object — no prose, no markdown, no
code fences. Use this exact shape:

{
  "overall_score": <int 0-100, LOWER = more original / safer>,
  "ai_likelihood": <int 0-100, HIGHER = more AI-generated>,
  "word_count": <int>,
  "summary": "<<=200 word plain-language explanation of the verdict>",
  "flagged_passages": [
    {
      "text": "<short excerpt from the input, <=180 chars>",
      "reason": "<short reason this passage was flagged>",
      "severity": "low" | "medium" | "high",
      "suggestion": "<one-line rewrite suggestion>"
    }
  ]
}

Return AT MOST 8 flagged passages. Only output JSON.
"""


REDUCE_SYSTEM_PROMPT = """You are a careful academic copy-editor. Rewrite
the user's text so it reads as more human-written and less templated:

- Vary sentence length and structure
- Replace AI-typical phrases ("delve into", "in conclusion", "it is
  important to note", etc.) with more natural alternatives
- Remove unnecessary hedging and boilerplate
- KEEP every factual claim, number, citation, and technical/medical term
  exactly as it appears
- KEEP all proper nouns
- Preserve the original meaning and structure of paragraphs

Respond with strict JSON only:

{
  "rewritten_text": "<the rewritten passage>",
  "changes_made": <int approximate number of edits made>,
  "notes": "<short note about the kinds of edits performed, <=200 chars>"
}

Only output JSON.
"""


# ---------------------------------------------------------------------------
# Provider calls
# ---------------------------------------------------------------------------


def _call_openai_json(system_prompt: str, user_text: str, *, max_tokens: int = 2000) -> Dict[str, Any]:
    """Call OpenAI Chat Completions with JSON response format."""
    client = _get_openai()
    # gpt-4o-mini is fast, cheap, and reliably honours JSON mode.
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_text},
        ],
        response_format={"type": "json_object"},
        max_tokens=max_tokens,
        temperature=0.2,
    )
    raw = resp.choices[0].message.content or "{}"
    return json.loads(raw)


def _call_gemini_json(system_prompt: str, user_text: str, *, max_tokens: int = 4096) -> Dict[str, Any]:
    """Call Gemini generate_content with JSON response MIME type."""
    from google.genai import types

    client = _get_gemini()
    # Gemini doesn't take a separate system prompt for generate_content,
    # so we prepend the instruction block as part of the user content.
    contents = f"{system_prompt}\n\n--- TEXT TO ANALYSE ---\n{user_text}"
    resp = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=contents,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            max_output_tokens=max_tokens,
            temperature=0.2,
        ),
    )
    raw = (resp.text or "").strip()
    return json.loads(raw)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

ProviderChoice = Literal["openai", "gemini", "auto"]


def _normalise_check_result(parsed: Dict[str, Any], *, fallback_word_count: int, model_used: str) -> Dict[str, Any]:
    """Coerce the LLM's JSON into the exact schema we promise to clients.

    Models occasionally drop a field or return scores as floats; this guard
    keeps the route handler ignorant of provider quirks.
    """
    overall = int(round(float(parsed.get("overall_score", 0))))
    ai_like = int(round(float(parsed.get("ai_likelihood", 0))))
    overall = max(0, min(100, overall))
    ai_like = max(0, min(100, ai_like))

    word_count = parsed.get("word_count")
    if not isinstance(word_count, int) or word_count <= 0:
        word_count = fallback_word_count

    summary = str(parsed.get("summary") or "").strip()

    flagged_raw = parsed.get("flagged_passages") or []
    flagged: list[Dict[str, Any]] = []
    if isinstance(flagged_raw, list):
        for item in flagged_raw[:8]:
            if not isinstance(item, dict):
                continue
            sev = str(item.get("severity") or "medium").lower()
            if sev not in ("low", "medium", "high"):
                sev = "medium"
            flagged.append({
                "text": str(item.get("text") or "").strip()[:240],
                "reason": str(item.get("reason") or "").strip()[:200],
                "severity": sev,
                "suggestion": str(item.get("suggestion") or "").strip()[:240],
            })

    return {
        "overall_score": overall,
        "ai_likelihood": ai_like,
        "word_count": word_count,
        "summary": summary,
        "flagged_passages": flagged,
        "model_used": model_used,
    }


def check_originality(text: str, *, provider: ProviderChoice = "auto") -> Dict[str, Any]:
    """Score originality + AI likelihood for ``text``.

    Strategy:
      * "auto" → try OpenAI first; if it raises, fall back to Gemini.
      * "openai" / "gemini" → use that provider only.
    """
    text = (text or "").strip()
    if not text:
        raise ValueError("text is empty")

    word_count = len(re.findall(r"\b\w+\b", text))

    if provider == "openai":
        parsed = _call_openai_json(CHECK_SYSTEM_PROMPT, text)
        return _normalise_check_result(parsed, fallback_word_count=word_count, model_used="openai")

    if provider == "gemini":
        parsed = _call_gemini_json(CHECK_SYSTEM_PROMPT, text)
        return _normalise_check_result(parsed, fallback_word_count=word_count, model_used="gemini")

    # auto — OpenAI first, Gemini fallback
    try:
        parsed = _call_openai_json(CHECK_SYSTEM_PROMPT, text)
        return _normalise_check_result(parsed, fallback_word_count=word_count, model_used="openai")
    except Exception as exc:  # noqa: BLE001
        log.warning("plagiarism.check openai failed, falling back to gemini: %s", exc)
        parsed = _call_gemini_json(CHECK_SYSTEM_PROMPT, text)
        return _normalise_check_result(parsed, fallback_word_count=word_count, model_used="gemini")


def reduce_plagiarism(text: str, *, provider: ProviderChoice = "auto") -> Dict[str, Any]:
    """Rewrite ``text`` to read more human and less templated."""
    text = (text or "").strip()
    if not text:
        raise ValueError("text is empty")

    def _normalise(parsed: Dict[str, Any], *, model_used: str) -> Dict[str, Any]:
        rewritten = str(parsed.get("rewritten_text") or "").strip()
        if not rewritten:
            # Models occasionally return the rewrite under a different key.
            rewritten = str(parsed.get("text") or parsed.get("rewrite") or "").strip()
        # Treat an empty rewrite as a provider failure so the auto-fallback
        # path can try the other provider and the route layer can return a
        # 502 instead of a misleading 200 with blank output.
        if not rewritten:
            raise RuntimeError("Provider returned an empty rewrite.")
        changes = parsed.get("changes_made")
        if not isinstance(changes, int):
            try:
                changes = int(changes)
            except Exception:
                changes = 0
        return {
            "original_text": text,
            "rewritten_text": rewritten,
            "changes_made": max(0, changes),
            "notes": str(parsed.get("notes") or "").strip()[:400],
            "model_used": model_used,
        }

    if provider == "openai":
        return _normalise(_call_openai_json(REDUCE_SYSTEM_PROMPT, text, max_tokens=4096), model_used="openai")
    if provider == "gemini":
        return _normalise(_call_gemini_json(REDUCE_SYSTEM_PROMPT, text, max_tokens=8192), model_used="gemini")
    try:
        return _normalise(_call_openai_json(REDUCE_SYSTEM_PROMPT, text, max_tokens=4096), model_used="openai")
    except Exception as exc:  # noqa: BLE001
        log.warning("plagiarism.reduce openai failed, falling back to gemini: %s", exc)
        return _normalise(_call_gemini_json(REDUCE_SYSTEM_PROMPT, text, max_tokens=8192), model_used="gemini")


# ---------------------------------------------------------------------------
# File-text extraction
# ---------------------------------------------------------------------------


def extract_text_from_upload(filename: str, content: bytes) -> str:
    """Pull plain text from an uploaded PDF / DOCX / TXT file.

    Falls back to a UTF-8 decode for unknown extensions. Files larger than
    a sensible cap are rejected at the route layer, not here.
    """
    name = (filename or "").lower()
    if name.endswith(".txt") or name.endswith(".md"):
        try:
            return content.decode("utf-8", errors="replace")
        except Exception:
            return content.decode("latin-1", errors="replace")

    if name.endswith(".pdf"):
        from io import BytesIO
        from pypdf import PdfReader

        reader = PdfReader(BytesIO(content))
        parts: list[str] = []
        for page in reader.pages:
            try:
                parts.append(page.extract_text() or "")
            except Exception:
                continue
        return "\n\n".join(p for p in parts if p.strip())

    if name.endswith(".docx"):
        from io import BytesIO
        import docx  # python-docx

        doc = docx.Document(BytesIO(content))
        return "\n".join(p.text for p in doc.paragraphs if p.text)

    # Last-ditch: try plain decode.
    try:
        return content.decode("utf-8", errors="replace")
    except Exception:
        return ""
