"""Plagiarism & AI-likelihood analysis service.

This module wraps two LLM providers — OpenAI and Google Gemini — behind a
small functional API used by the ``/api/plagiarism`` routes. The two
providers are interchangeable per call: callers pick "openai", "gemini",
or "auto" (try OpenAI first, fall back to Gemini).

Important honesty note
----------------------
Pure-LLM "plagiarism detection" cannot search the web or compare against
a copyrighted corpus. What this service actually does is:

  * Score how *AI-generated-sounding* the text reads (prompt patterns,
    boilerplate phrases, generic transitions).
  * Score how *unoriginal/templated* the prose looks against common
    academic clichés.
  * Flag specific passages and propose rewrites.

The combined "overall_score" is a heuristic the model returns. We surface
it transparently in the UI rather than pretending it's an authoritative
match against a database.
"""

from __future__ import annotations

import difflib
import json
import os
import re
import time
from typing import Any, Dict, List, Literal, Optional

from app.core.logging import get_logger

log = get_logger(__name__)


# ---------------------------------------------------------------------------
# Lazy-initialised SDK clients
# ---------------------------------------------------------------------------

def _get_openai():
    """Return a fresh OpenAI client via the integration proxy or direct key."""
    from app.services.llm_client import get_openai_client
    return get_openai_client()


def _get_gemini():
    """Return a fresh google-genai client via the integration proxy or direct key."""
    from app.services.llm_client import get_gemini_client
    return get_gemini_client()


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

CHECK_SYSTEM_PROMPT = """You are an experienced academic-writing originality
analyst. Given a passage of text, you assess two things:

1) ORIGINALITY: how much of the writing reads as templated, boilerplate, or
   commonly-recycled academic phrasing (NOT a database match — a heuristic
   based on language patterns).
2) AI-LIKELIHOOD: how much the writing reads as machine-generated by a
   modern LLM (cadence, transitions, hedging language, generic phrasing).

You MUST respond with a strict JSON object — no prose, no markdown, no
code fences. Use this exact shape:

{
  "overall_score": <int 0-100, LOWER = more original / safer>,
  "ai_likelihood": <int 0-100, HIGHER = more AI-generated>,
  "word_count": <int>,
  "summary": "<<=200 word plain-language explanation of the verdict>",
  "flagged_passages": [
    {
      "text": "<short excerpt from the input, <=180 chars>",
      "reason": "<short reason this passage was flagged>",
      "severity": "low" | "medium" | "high",
      "suggestion": "<one-line rewrite suggestion>"
    }
  ]
}

Return AT MOST 8 flagged passages. Only output JSON.
"""


REDUCE_SYSTEM_PROMPT = """You are a careful academic copy-editor. Rewrite
the user's text so it reads as more human-written and less templated:

- Vary sentence length and structure
- Replace AI-typical phrases ("delve into", "in conclusion", "it is
  important to note", etc.) with more natural alternatives
- Remove unnecessary hedging and boilerplate
- KEEP every factual claim, number, citation, and technical/medical term
  exactly as it appears
- KEEP all proper nouns
- Preserve the original meaning and structure of paragraphs

Respond with strict JSON only:

{
  "rewritten_text": "<the rewritten passage>",
  "changes_made": <int approximate number of edits made>,
  "notes": "<short note about the kinds of edits performed, <=200 chars>"
}

Only output JSON.
"""


def _build_protected_terms_block(terms: list[str] | None) -> str:
    """Return an extra prompt block listing strings that must NOT change.

    The detector upstream gives us drug names, p-values, percentages, dose
    units, citations, DOIs, gene symbols, ICD codes, and similar. We
    surface them to the model as a hard constraint so the rewrite cannot
    quietly paraphrase "p < 0.001" into "highly significant" or rename a
    drug.
    """
    if not terms:
        return ""
    # Cap the injected list to keep the prompt within reason. The detector
    # already enforces 400 — we further trim for prompt economy.
    capped = terms[:200]
    items = "\n".join(f"  - {t}" for t in capped)
    return (
        "\n\nPROTECTED STRINGS — these substrings MUST appear in the "
        "rewritten text EXACTLY as written, without any paraphrasing, "
        "reformatting, or capitalisation changes. Do not translate units. "
        "Do not round numbers. Do not drop citation brackets.\n"
        f"{items}\n"
    )


# ---------------------------------------------------------------------------
# Provider calls
# ---------------------------------------------------------------------------


def _call_openai_json(system_prompt: str, user_text: str, *, max_tokens: int = 2000) -> Dict[str, Any]:
    """Call OpenAI Chat Completions with JSON response format."""
    client = _get_openai()
    # gpt-4o-mini is fast, cheap, and reliably honours JSON mode.
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_text},
        ],
        response_format={"type": "json_object"},
        max_tokens=max_tokens,
        temperature=0.2,
    )
    raw = resp.choices[0].message.content or "{}"
    return json.loads(raw)


# ---------------------------------------------------------------------------
# Plain-text provider calls (used by the 3-stage rewrite pipeline)
# ---------------------------------------------------------------------------


# Markers for errors that mean "your account is out of credits / requests
# for this provider — retrying will NEVER help". Checked BEFORE the
# transient marker check so a 429 with insufficient_quota doesn't get
# retried 3 times pointlessly.
_QUOTA_EXHAUSTED_MARKERS = (
    "insufficient_quota",
    "exceeded your current quota",
    "resource_exhausted",
    "quota exceeded",
    "billing",
)

# Markers for errors that are likely transient and worth retrying.
_TRANSIENT_MARKERS = (
    "503", "unavailable", "overloaded",
    "rate_limit", "rate limit",
    "timeout", "timed out", "deadline exceeded",
    "service unavailable", "connection reset", "connection error",
)


class ProviderQuotaExhausted(RuntimeError):
    """Raised when a provider is permanently out of quota for this billing
    period. Distinct from a transient error so the route layer can return
    a clear, actionable 503 instead of a generic 502.
    """


def _is_quota_exhausted_error(exc: Exception) -> bool:
    msg = (str(exc) or "").lower()
    return any(m in msg for m in _QUOTA_EXHAUSTED_MARKERS)


def _is_transient_error(exc: Exception) -> bool:
    """True for errors that are likely to succeed on retry. Quota errors
    are explicitly excluded — they're permanent for the billing period."""
    if _is_quota_exhausted_error(exc):
        return False
    msg = (str(exc) or "").lower()
    return any(m in msg for m in _TRANSIENT_MARKERS)


def _with_retry(fn, *, attempts: int = 3, base_delay: float = 1.5):
    """Call ``fn()`` up to ``attempts`` times with exponential backoff on
    transient errors (503/timeout/overloaded). Quota-exhaustion errors
    are re-raised IMMEDIATELY (no retry, no backoff) so the caller can
    fall back to the other provider in seconds rather than minutes.
    """
    import time
    last_exc: Optional[Exception] = None
    for attempt in range(attempts):
        try:
            return fn()
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            if _is_quota_exhausted_error(exc):
                # Permanent. Don't retry. Don't waste the user's time.
                log.warning("provider quota exhausted, no retry: %s", str(exc)[:200])
                raise
            if not _is_transient_error(exc) or attempt == attempts - 1:
                raise
            delay = base_delay * (2 ** attempt)
            log.warning("transient provider error (attempt %d/%d, retry in %.1fs): %s",
                        attempt + 1, attempts, str(exc)[:200])
            time.sleep(delay)
    if last_exc:
        raise last_exc
    raise RuntimeError("retry loop exited without result")


def _strip_fences(s: str) -> str:
    """Strip accidental ``` code fences and leading/trailing blank lines."""
    s = (s or "").strip()
    if s.startswith("```"):
        nl = s.find("\n")
        if nl != -1:
            s = s[nl + 1 :]
        if s.endswith("```"):
            s = s[:-3]
    return s.strip()


def _call_openai_text(
    system_prompt: str,
    user_text: str,
    *,
    model: str = "gpt-4o",
    max_tokens: int = 4096,
    temperature: float = 0.4,
    timeout: Optional[float] = None,
) -> str:
    """Call OpenAI Chat Completions and return plain-text content.

    ``timeout`` is forwarded to the SDK so the underlying socket
    actually closes when we want to give up — without it, an outer
    wall-clock timeout still leaves the LLM call running on the OpenAI
    side, burning tokens.
    """
    client = _get_openai()
    kwargs: Dict[str, Any] = dict(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_text},
        ],
        max_tokens=max_tokens,
        temperature=temperature,
    )
    if timeout is not None:
        kwargs["timeout"] = float(timeout)
    resp = client.chat.completions.create(**kwargs)
    return _strip_fences(resp.choices[0].message.content or "")


def _call_gemini_text(
    system_prompt: str,
    user_text: str,
    *,
    max_tokens: int = 8192,
    temperature: float = 0.4,
    timeout: Optional[float] = None,
) -> str:
    """Call Gemini generate_content and return plain-text content.

    ``timeout`` is forwarded via ``http_options`` so the underlying
    httpx client honours it. Same rationale as ``_call_openai_text``:
    we never want the network call outlasting the wall-clock budget
    or we'll keep paying for tokens after we've already given up.
    """
    from google.genai import types

    client = _get_gemini()
    contents = f"{system_prompt}\n\n--- TEXT ---\n{user_text}"
    cfg_kwargs: Dict[str, Any] = dict(
        max_output_tokens=max_tokens,
        temperature=temperature,
    )
    if timeout is not None:
        # google-genai accepts http_options.timeout in MILLISECONDS.
        cfg_kwargs["http_options"] = types.HttpOptions(timeout=int(timeout * 1000))
    resp = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=contents,
        config=types.GenerateContentConfig(**cfg_kwargs),
    )
    return _strip_fences(resp.text or "")


def _call_gemini_json(system_prompt: str, user_text: str, *, max_tokens: int = 4096) -> Dict[str, Any]:
    """Call Gemini generate_content with JSON response MIME type."""
    from google.genai import types

    client = _get_gemini()
    # Gemini doesn't take a separate system prompt for generate_content,
    # so we prepend the instruction block as part of the user content.
    contents = f"{system_prompt}\n\n--- TEXT TO ANALYSE ---\n{user_text}"
    resp = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=contents,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            max_output_tokens=max_tokens,
            temperature=0.2,
        ),
    )
    raw = (resp.text or "").strip()
    return json.loads(raw)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

ProviderChoice = Literal["openai", "gemini", "auto"]


def _normalise_check_result(parsed: Dict[str, Any], *, fallback_word_count: int, model_used: str) -> Dict[str, Any]:
    """Coerce the LLM's JSON into the exact schema we promise to clients.

    Models occasionally drop a field or return scores as floats; this guard
    keeps the route handler ignorant of provider quirks.
    """
    overall = int(round(float(parsed.get("overall_score", 0))))
    ai_like = int(round(float(parsed.get("ai_likelihood", 0))))
    overall = max(0, min(100, overall))
    ai_like = max(0, min(100, ai_like))

    word_count = parsed.get("word_count")
    if not isinstance(word_count, int) or word_count <= 0:
        word_count = fallback_word_count

    summary = str(parsed.get("summary") or "").strip()

    flagged_raw = parsed.get("flagged_passages") or []
    flagged: list[Dict[str, Any]] = []
    if isinstance(flagged_raw, list):
        for item in flagged_raw[:8]:
            if not isinstance(item, dict):
                continue
            sev = str(item.get("severity") or "medium").lower()
            if sev not in ("low", "medium", "high"):
                sev = "medium"
            flagged.append({
                "text": str(item.get("text") or "").strip()[:240],
                "reason": str(item.get("reason") or "").strip()[:200],
                "severity": sev,
                "suggestion": str(item.get("suggestion") or "").strip()[:240],
            })

    return {
        "overall_score": overall,
        "ai_likelihood": ai_like,
        "word_count": word_count,
        "summary": summary,
        "flagged_passages": flagged,
        "model_used": model_used,
    }


def check_originality(text: str, *, provider: ProviderChoice = "auto") -> Dict[str, Any]:
    """Score originality + AI likelihood for ``text``.

    Strategy:
      * "auto" → try OpenAI first; if it raises, fall back to Gemini.
      * "openai" / "gemini" → use that provider only.
    """
    text = (text or "").strip()
    if not text:
        raise ValueError("text is empty")

    word_count = len(re.findall(r"\b\w+\b", text))

    if provider == "openai":
        parsed = _call_openai_json(CHECK_SYSTEM_PROMPT, text)
        return _normalise_check_result(parsed, fallback_word_count=word_count, model_used="openai")

    if provider == "gemini":
        parsed = _call_gemini_json(CHECK_SYSTEM_PROMPT, text)
        return _normalise_check_result(parsed, fallback_word_count=word_count, model_used="gemini")

    # auto — OpenAI first, Gemini fallback
    try:
        parsed = _call_openai_json(CHECK_SYSTEM_PROMPT, text)
        return _normalise_check_result(parsed, fallback_word_count=word_count, model_used="openai")
    except Exception as exc:  # noqa: BLE001
        log.warning("plagiarism.check openai failed, falling back to gemini: %s", exc)
        parsed = _call_gemini_json(CHECK_SYSTEM_PROMPT, text)
        return _normalise_check_result(parsed, fallback_word_count=word_count, model_used="gemini")


def reduce_plagiarism(
    text: str,
    *,
    provider: ProviderChoice = "auto",
    protected_terms: Optional[list[str]] = None,
) -> Dict[str, Any]:
    """Rewrite ``text`` to read more human and less templated.

    If ``protected_terms`` is supplied, those exact substrings are surfaced
    to the LLM as hard "do not paraphrase" constraints, AND we verify
    afterwards that each one still appears in the rewrite — any missing
    terms are returned in the ``preserved_terms_missing`` field so the UI
    can warn the user.
    """
    text = (text or "").strip()
    if not text:
        raise ValueError("text is empty")

    system_prompt = REDUCE_SYSTEM_PROMPT + _build_protected_terms_block(protected_terms)

    def _normalise(parsed: Dict[str, Any], *, model_used: str) -> Dict[str, Any]:
        rewritten = str(parsed.get("rewritten_text") or "").strip()
        if not rewritten:
            # Models occasionally return the rewrite under a different key.
            rewritten = str(parsed.get("text") or parsed.get("rewrite") or "").strip()
        # Treat an empty rewrite as a provider failure so the auto-fallback
        # path can try the other provider and the route layer can return a
        # 502 instead of a misleading 200 with blank output.
        if not rewritten:
            raise RuntimeError("Provider returned an empty rewrite.")
        changes = parsed.get("changes_made")
        if not isinstance(changes, int):
            try:
                changes = int(changes)
            except Exception:
                changes = 0
        # Verify protected terms survived the rewrite. Any that didn't are
        # surfaced for the UI to flag — we don't fail the whole call because
        # often the missing term IS still present, just with a paraphrased
        # boundary (e.g. trailing punctuation differs).
        missing: list[str] = []
        if protected_terms:
            for term in protected_terms:
                if term and term not in rewritten:
                    missing.append(term)
        return {
            "original_text": text,
            "rewritten_text": rewritten,
            "changes_made": max(0, changes),
            "notes": str(parsed.get("notes") or "").strip()[:400],
            "model_used": model_used,
            "protected_terms_count": len(protected_terms or []),
            "preserved_terms_missing": missing[:50],
        }

    if provider == "openai":
        return _normalise(_call_openai_json(system_prompt, text, max_tokens=4096), model_used="openai")
    if provider == "gemini":
        return _normalise(_call_gemini_json(system_prompt, text, max_tokens=8192), model_used="gemini")
    try:
        return _normalise(_call_openai_json(system_prompt, text, max_tokens=4096), model_used="openai")
    except Exception as exc:  # noqa: BLE001
        log.warning("plagiarism.reduce openai failed, falling back to gemini: %s", exc)
        return _normalise(_call_gemini_json(system_prompt, text, max_tokens=8192), model_used="gemini")


# ---------------------------------------------------------------------------
# 3-stage rewrite pipeline
# ---------------------------------------------------------------------------
#
# When the user clicks "Reduce plagiarism" on an analysed upload, we run
# each detected section through three sequential LLM stages:
#
#   A. Paraphrase-for-originality    — primary: OpenAI gpt-4o
#   B. De-AI / humanise              — primary: Gemini gemini-2.5-flash
#   C. Quality-and-flow polish pass  — primary: OpenAI gpt-4o
#
# Each stage falls back to the OTHER provider if its primary fails (so the
# pipeline still completes when, e.g., the OpenAI key is over quota). The
# References / Bibliography section is skipped entirely — academic refs
# must NEVER be paraphrased or "humanised". Protected terms (drug names,
# p-values, citations, etc.) are surfaced as a hard constraint to every
# stage and verified post-hoc on the combined output.

# ---------------------------------------------------------------------------
# AI residual scoring
# ---------------------------------------------------------------------------
# After the 3-stage pipeline, we score the final text for residual AI
# patterns using two heuristics:
#   (1) Phrase density — how many of the known AI-filler phrases from
#       Stage B's blacklist still appear per 1000 words.
#   (2) Sentence-length uniformity — the coefficient of variation (CV) of
#       sentence word-counts. AI text has suspiciously uniform lengths
#       (CV ≈ 0.2–0.35); human academic prose is more erratic (CV > 0.45).
# Both sub-scores are combined into a 0–100 composite (0 = clean / human,
# 100 = AI-like) and bucketed into a labelled colour key.

_AI_RESIDUAL_PHRASES: tuple = (
    "moreover", "furthermore", "additionally", "in conclusion",
    "it is important to note", "it is worth noting", "notably",
    "it should be noted that", "it can be argued that",
    "generally speaking", "it has been shown that",
    "studies have demonstrated", "delve into",
    "in summary", "to summarize", "essentially",
    "nuanced", "multifaceted", "robust", "comprehensive",
    "tapestry", "underscore", "showcase", "leverage",
    "facilitate", "utilize", "overall",
)


def _score_ai_residual(text: str) -> Dict[str, Any]:
    """Heuristic AI-pattern residual score for the rewritten text.

    Returns dict:
      ``ai_risk_score``  int 0-100  (0 = very human-like, 100 = AI-like)
      ``ai_risk_label``  str        e.g. "Very Low", "Low", …
      ``ai_risk_key``    str        one of green / yellow / orange / red / gray
    """
    stripped = text.strip()
    if not stripped:
        return {"ai_risk_score": 0, "ai_risk_label": "N/A", "ai_risk_key": "gray"}

    lower = stripped.lower()
    word_count = max(1, len(re.findall(r"\b\w+\b", lower)))

    # ---- sub-score 1: phrase density (per 1000 words, capped at 100) ----
    phrase_hits = sum(lower.count(p) for p in _AI_RESIDUAL_PHRASES)
    phrase_score = min(100, round(phrase_hits / word_count * 1000))

    # ---- sub-score 2: sentence-length uniformity ----
    sentences = [s.strip() for s in re.split(r"[.!?]+", stripped)
                 if len(s.strip().split()) > 2]
    if len(sentences) >= 5:
        lengths = [len(s.split()) for s in sentences]
        mean_len = sum(lengths) / len(lengths)
        std_dev = (sum((l - mean_len) ** 2 for l in lengths) / len(lengths)) ** 0.5
        cv = std_dev / max(1.0, mean_len)
        # CV ≥ 0.55 → richly varied (0 risk); CV ≤ 0.20 → robot-flat (100 risk)
        uniformity_score = max(0, min(100, round((0.55 - cv) / 0.35 * 100)))
    else:
        uniformity_score = 20  # too few sentences to judge

    composite = round(0.55 * phrase_score + 0.45 * uniformity_score)

    if composite <= 12:
        label, key = "Very Low", "green"
    elif composite <= 30:
        label, key = "Low", "green"
    elif composite <= 55:
        label, key = "Moderate", "yellow"
    elif composite <= 75:
        label, key = "High", "orange"
    else:
        label, key = "Very High", "red"

    return {"ai_risk_score": composite, "ai_risk_label": label, "ai_risk_key": key}

STAGE_A_PARAPHRASE_PROMPT = """You are Novus — a specialist academic paraphrase engine designed for medical and scientific manuscripts. Your task is PARAPHRASE-FOR-ORIGINALITY: restructure the passage so it expresses identical ideas through substantially different vocabulary, sentence architecture, and paragraph rhythm, targeting <10% surface similarity to common academic phrasing while fully preserving academic rigour.

WHAT MAKES NOVUS DIFFERENT FROM A GENERIC PARAPHRASER:
- You are NOT a synonym-swapper. You reconstruct sentence structure, not just individual words.
- You preserve every technical and scientific term exactly — they are anchors, not targets.
- You maintain the logical flow and argumentative weight of each paragraph.
- The rewritten text must read as if written by the same expert author, not a different one.

PARAPHRASE TECHNIQUES TO APPLY:
- Change sentence order within paragraphs where logically permissible.
- Convert passive constructions to active and vice versa (where each improves clarity).
- Merge two short sentences into one compound-complex sentence, or split one long sentence into two.
- Replace generic academic openers ("This study aimed to", "The results showed that") with specific, information-forward openers.
- Vary clause position: move temporal, causal, or conditional clauses from end to beginning or vice versa.
- Use discipline-appropriate synonyms for non-technical words (e.g. "evaluate" → "assess", "indicate" → "suggest", "demonstrate" → "reveal").

ABSOLUTE HARD RULES — NEVER VIOLATE:
- Every protected string listed below MUST appear in your output EXACTLY as written, character-for-character. No capitalisation changes, no unit changes, no rounding.
- Preserve every numeric value, p-value, confidence interval, odds ratio, hazard ratio, drug name, gene symbol, diagnostic criterion, citation marker, and DOI exactly.
- Do NOT add new claims, data, or interpretations. Do NOT remove existing information.
- Preserve paragraph breaks. Keep any section heading on its own line at the top, unchanged.
- The meaning, conclusions, and academic standard of the original MUST be fully retained.

Output ONLY the rewritten text — no preamble, no JSON, no code fences, no commentary.
"""

STAGE_B_HUMANIZE_PROMPT = """You are Novus — a specialist AI-signature removal engine. Your task is to make the passage below read as if written by an experienced human medical researcher, eliminating EVERY pattern that AI-detection systems (GPTZero, Turnitin AI, Copyleaks AI, Originality.ai) recognise as machine-generated. Target: 0% AI detection score.

WHAT AI-DETECTION SYSTEMS LOOK FOR (eliminate ALL of these):
1. Uniform sentence length — AI consistently produces sentences of similar word count. Vary sharply: some 6-word sentences, some 30-word sentences, with unpredictable rhythm.
2. Perfectly balanced paragraph structure — AI balances paragraphs symmetrically. Disrupt this: let some paragraphs be brief (2-3 sentences), others longer.
3. Formulaic transition words — eliminate: "Moreover", "Furthermore", "Additionally", "In conclusion", "It is important to note", "It is worth noting", "Notably", "Importantly", "It should be noted that", "It can be argued that", "Significantly", "Essentially", "Overall", "In summary", "To summarize", "Delve into", "Robust", "Comprehensive", "Nuanced", "Multifaceted", "Navigate", "Tapestry", "Underscore", "Showcase", "Leverage", "Facilitate", "Utilize" (use "use" instead).
4. Hedging boilerplate — remove: "Generally speaking", "It is widely accepted that", "It has been shown that", "Studies have demonstrated that" (use specific citations instead).
5. Symmetrical list structures — AI loves "X, Y, and Z" triplets and tidy bulleted reasoning. Break symmetry: use two items sometimes, four other times.
6. Overly formal, even register — allow occasional informal academic phrasing, contractions in dialogue-style sections, sentences starting with "And" or "But", even one-sentence paragraphs for emphasis.
7. Predictable conclusion sentences — AI always ends paragraphs with a summary sentence. Break this pattern: sometimes end mid-thought, sometimes with a question or implication.

HARD RULES — NEVER VIOLATE:
- Every protected string listed below MUST appear in your output EXACTLY as written. Preserve all numbers, statistics, p-values, confidence intervals, citations, drug names, units, gene symbols, and DOIs.
- Preserve the meaning and academic integrity. Do NOT add new claims or remove information.
- Maintain the academic standard of a peer-reviewed medical manuscript.
- Preserve paragraph structure. Keep any section heading on its own line at the top, unchanged.

Output ONLY the revised text — no preamble, no JSON, no code fences, no commentary.
"""

STAGE_C_POLISH_PROMPT = """You are Novus — a senior medical journal editor performing the FINAL QUALITY PASS. Your goal is to ensure the passage reads as submission-ready academic prose: grammatically correct, scientifically precise, and at the standard of a high-impact peer-reviewed journal.

WHAT TO FIX:
- Grammar errors, subject-verb disagreement, dangling modifiers, incorrect tense.
- Broken or awkward transitions between sentences.
- Any sentence that reads unnaturally or loses scientific meaning.
- Repetition of the same word or phrase within two sentences of each other.
- Any accidental AI phrase that slipped through (check the list from Stage B).

WHAT NOT TO TOUCH:
- Sentences that already read cleanly — make NO change.
- The level of paraphrasing already achieved — do NOT revert to more original-sounding phrasing.
- The academic register — this must read like a medical researcher, not a generalist.

ABSOLUTE HARD RULES — NEVER VIOLATE:
- Every protected string listed below MUST appear in your output EXACTLY as written. Do not alter numbers, p-values, confidence intervals, drug names, citations, units, or DOIs in any way.
- Preserve the overall meaning and length. Do not add new claims, remove information, or substantially shorten.
- Preserve paragraph structure and any heading on its own line at the top.

Output ONLY the polished text — no preamble, no JSON, no code fences, no commentary.
"""

# Match labels that the analyzer uses for the references block. Anything
# matching this is skipped by the pipeline (kept verbatim in final output).
# Match section labels for reference lists. Tolerates a leading number
# prefix ("5. References", "5) References", "5 References") so labels
# coming straight from the section detector still match.
_REFERENCES_LABEL_RE = re.compile(
    r"^\s*(?:\d+\s*[\.\)]?\s+)?(?:references?|bibliography|works\s+cited|literature\s+cited)\b",
    re.IGNORECASE,
)


def _is_references_label(label: str) -> bool:
    return bool(_REFERENCES_LABEL_RE.match(label or ""))


def _approx_word_edits(before: str, after: str) -> int:
    """Heuristic count of token-level edits between two strings.

    Used only to populate the ``changes_made`` counter shown in the UI.
    Not a quality metric — just a rough indicator.
    """
    a = re.findall(r"\S+", before or "")
    b = re.findall(r"\S+", after or "")
    if not a and not b:
        return 0
    sm = difflib.SequenceMatcher(None, a, b, autojunk=False)
    edits = 0
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        edits += max(i2 - i1, j2 - j1)
    return edits


def _run_stage(
    *,
    primary: Literal["openai", "gemini"],
    system_prompt: str,
    user_text: str,
    protected_terms: Optional[List[str]],
    stage_label: str,
    sdk_timeout: Optional[float] = None,
    temperature: float = 0.4,
) -> Dict[str, Any]:
    """Run one stage with primary-provider preference and other-provider fallback.

    ``sdk_timeout`` (seconds), when supplied, is forwarded to the OpenAI
    and Gemini SDKs so the network call itself closes when we time out
    — important for the job-based pipeline so an abandoned future does
    not keep burning tokens server-side.

    Returns a dict with keys:
      ``text``           — the stage output (non-empty),
      ``model``          — human-readable provider label (e.g. "gpt-4o" or
                           "gemini-2.5-flash (fallback)"),
      ``fallback_used``  — bool, true if the primary failed.
    """
    full_prompt = system_prompt + _build_protected_terms_block(protected_terms)
    primary_err: Optional[str] = None

    def _openai_call() -> str:
        return _with_retry(lambda: _call_openai_text(
            full_prompt, user_text, model="gpt-4o", timeout=sdk_timeout, temperature=temperature,
        ))

    def _gemini_call() -> str:
        return _with_retry(lambda: _call_gemini_text(
            full_prompt, user_text, timeout=sdk_timeout, temperature=temperature,
        ))

    def _try_fallback(
        other_call,
        other_label: str,
        primary_exc: Exception,
    ) -> Dict[str, Any]:
        primary_err_str = f"{type(primary_exc).__name__}: {primary_exc}"
        primary_was_quota = _is_quota_exhausted_error(primary_exc)
        try:
            text = other_call()
        except Exception as fb_exc:  # noqa: BLE001
            fallback_was_quota = _is_quota_exhausted_error(fb_exc)
            # Only raise ProviderQuotaExhausted when BOTH providers failed
            # specifically with quota errors. Otherwise (e.g. transient 503
            # on one side, quota on the other) propagate the fallback
            # exception so the route returns its normal 502 with the real
            # cause — we do NOT want to mislead the user with a "both out
            # of quota" message when only one provider actually was.
            if primary_was_quota and fallback_was_quota:
                raise ProviderQuotaExhausted(
                    f"Stage {stage_label}: both providers exhausted. "
                    f"Primary error: {primary_err_str[:300]}. "
                    f"Fallback error: {str(fb_exc)[:300]}"
                ) from fb_exc
            raise
        if not text:
            raise RuntimeError(f"Stage {stage_label}: both providers returned empty output")
        return {"text": text, "model": f"{other_label} (fallback)", "fallback_used": True, "primary_error": primary_err_str}

    if primary == "openai":
        try:
            text = _openai_call()
            if text:
                return {"text": text, "model": "gpt-4o", "fallback_used": False, "primary_error": None}
            raise RuntimeError("Empty output from gpt-4o")
        except Exception as exc:  # noqa: BLE001
            log.warning("pipeline %s: openai primary failed (%s) — falling back to gemini", stage_label, str(exc)[:200])
            return _try_fallback(_gemini_call, "gemini-2.5-flash", exc)
    else:
        try:
            text = _gemini_call()
            if text:
                return {"text": text, "model": "gemini-2.5-flash", "fallback_used": False, "primary_error": None}
            raise RuntimeError("Empty output from gemini")
        except Exception as exc:  # noqa: BLE001
            log.warning("pipeline %s: gemini primary failed (%s) — falling back to openai", stage_label, str(exc)[:200])
            return _try_fallback(_openai_call, "gpt-4o", exc)


class PipelineCancelled(RuntimeError):
    """Raised when a streaming consumer disconnects mid-pipeline.

    The route-level handler suppresses this so we don't log it as a real
    error — it's just the worker thread cooperatively bailing out so we
    don't keep burning LLM credits on a request nobody is listening to.
    """


class StageTimeoutError(RuntimeError):
    """A single pipeline stage exceeded its hard wall-clock timeout.

    Raised by ``process_one_section`` so the job manager can mark that
    section as ``timed_out`` and proceed with the next section instead of
    blocking the whole job on a slow provider.
    """


def _run_stage_with_timeout(
    *,
    primary: Literal["openai", "gemini"],
    system_prompt: str,
    user_text: str,
    protected_terms: Optional[List[str]],
    stage_label: str,
    timeout_seconds: float,
    temperature: float = 0.4,
) -> Dict[str, Any]:
    """Wrap ``_run_stage`` with a hard wall-clock timeout.

    The provider SDKs run synchronous network I/O that can hang well past
    their nominal timeouts (proxy stalls, server-side queueing). We submit
    the call to a fresh worker thread and abandon it if it exceeds
    ``timeout_seconds``. The orphaned thread will eventually finish or
    error out — we just stop waiting on it. Cost: at most one in-flight
    abandoned call per timed-out stage.
    """
    import concurrent.futures
    # Give the SDK a slightly tighter budget than the wall-clock so the
    # underlying socket closes BEFORE we abandon the future. This is
    # what stops us from paying for tokens after we've given up.
    sdk_timeout = max(5.0, timeout_seconds - 2.0)
    # Use a non-context-managed executor so an orphaned thread doesn't
    # block our return — context-managed executors join all threads on
    # __exit__, which would re-introduce the very hang we're avoiding.
    ex = concurrent.futures.ThreadPoolExecutor(
        max_workers=1, thread_name_prefix=f"pm-stage-{stage_label}"
    )
    try:
        fut = ex.submit(
            _run_stage,
            primary=primary,
            system_prompt=system_prompt,
            user_text=user_text,
            protected_terms=protected_terms,
            stage_label=stage_label,
            sdk_timeout=sdk_timeout,
            temperature=temperature,
        )
        try:
            return fut.result(timeout=timeout_seconds)
        except concurrent.futures.TimeoutError as exc:
            # The SDK timeout (sdk_timeout) should have already started
            # tearing down the socket. We don't block waiting for it —
            # we abandon the future and raise.
            fut.cancel()
            raise StageTimeoutError(
                f"Stage {stage_label} timed out after {timeout_seconds:.0f}s"
            ) from exc
    finally:
        # wait=False: do NOT block on any orphaned worker thread.
        ex.shutdown(wait=False)


# ---------------------------------------------------------------------------
# Large-section chunking
# ---------------------------------------------------------------------------
# Sections longer than this word count are split into paragraph-aligned
# chunks before the 3-stage pipeline runs. Each chunk is processed
# independently; outputs are reassembled in order. This keeps individual
# LLM calls well within context limits and improves paraphrase quality —
# the model produces better diversity on a focused 600-word block than when
# it must simultaneously track 3000 words.

_CHUNK_WORD_THRESHOLD = 900   # words; sections larger than this are chunked
_CHUNK_TARGET_WORDS   = 600   # target words per chunk


def _split_into_chunks(text: str, target_words: int = _CHUNK_TARGET_WORDS) -> List[str]:
    """Split ``text`` into ≈target_words-word chunks at paragraph boundaries.

    Paragraph integrity is preserved — a paragraph is never broken
    mid-sentence. If a single paragraph exceeds 2× target_words it is
    accepted as an oversized chunk rather than being split in the middle.
    """
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", text.strip()) if p.strip()]
    if not paragraphs:
        return [text]

    chunks: List[str] = []
    current: List[str] = []
    current_words = 0

    for para in paragraphs:
        para_words = len(re.findall(r"\b\w+\b", para))
        if current_words + para_words > target_words and current:
            chunks.append("\n\n".join(current))
            current = [para]
            current_words = para_words
        else:
            current.append(para)
            current_words += para_words

    if current:
        chunks.append("\n\n".join(current))

    return chunks if chunks else [text]


def process_one_section(
    *,
    index: int,
    label: str,
    text: str,
    protected_terms: Optional[List[str]] = None,
    stage_timeout: float = 60.0,
    progress_cb: Optional[Any] = None,
    intensity: str = "normal",
) -> Dict[str, Any]:
    """Run the rewrite on ONE section with per-stage timeout.

    Always returns a dict — never raises ordinary errors. The only thing
    that propagates is :class:`ProviderQuotaExhausted`, which the caller
    treats specially (no point retrying further sections when both
    providers are out).

    ``intensity`` controls how much rewriting we do — used by the
    plagiarism-report path so we don't waste compute on sections that
    already came back clean from Turnitin/Drillbit/etc.:

      * ``"skip"``       — return original unchanged (already acceptable)
      * ``"light"``      — only stages A + B (paraphrase + humanise),
                           skip the polish pass
      * ``"normal"``     — full 3-stage rewrite (default)
      * ``"aggressive"`` — full 3-stage rewrite (same path as normal,
                           but tagged so the UI can flag the section)

    The returned dict has ``status`` set to one of:

      * ``"complete"``  — rewrite succeeded
      * ``"skipped"``   — empty section, References, or below-threshold
                          (intensity="skip")
      * ``"timed_out"`` — at least one stage exceeded ``stage_timeout``
      * ``"failed"``    — a non-quota error occurred (network, parse, etc.)

    ``progress_cb`` (if supplied) is called as ``cb(pass_num, label)``
    after each stage starts (1-indexed: 1=A, 2=B, 3=C).
    """
    label = (label or "").strip() or f"Section {index+1}"
    body = (text or "").strip()

    base_entry = {
        "index": index,
        "label": label,
        "original": body,
        "stage_a_text": "",
        "stage_b_text": "",
        "stage_c_text": "",
        "final_text": "",
        "stage_models": {},
        "edits": 0,
        "missing_terms": [],
        "fallback_used": False,
        "elapsed_seconds": 0.0,
        "error": None,
    }

    if not body:
        return {
            **base_entry,
            "status": "skipped",
            "skipped": True,
            "skip_reason": "empty",
            "quality": {"key": "gray", "label": "Empty", "hint": "No content to rewrite."},
        }

    if _is_references_label(label):
        return {
            **base_entry,
            "status": "skipped",
            "skipped": True,
            "skip_reason": "references",
            "final_text": body,  # kept verbatim
            "intensity": "skip",
            "quality": {"key": "gray", "label": "Kept verbatim", "hint": "References are never paraphrased."},
        }

    # Plagiarism-report intensity: caller said this section is already
    # below the similarity threshold — skip rewriting entirely.
    if intensity == "skip":
        return {
            **base_entry,
            "status": "skipped",
            "skipped": True,
            "skip_reason": "below_threshold",
            "final_text": body,  # kept verbatim
            "intensity": "skip",
            "quality": {
                "key": "green",
                "label": "Already within acceptable limits — not rewritten",
                "hint": "Your plagiarism report flagged this section below the rewrite threshold, so it has been kept verbatim.",
            },
        }

    section_terms = [t for t in (protected_terms or []) if t and t in body]
    started = time.monotonic()
    light_mode = (intensity == "light")  # skip the Stage C polish pass

    # Split large sections into paragraph-aligned chunks so each LLM call
    # stays focused and produces higher-quality paraphrase diversity.
    _word_count = len(re.findall(r"\b\w+\b", body))
    chunks = _split_into_chunks(body) if _word_count > _CHUNK_WORD_THRESHOLD else [body]
    n_chunks = len(chunks)

    def _cb(num: int, lbl: str) -> None:
        if progress_cb is None:
            return
        try:
            progress_cb(num, lbl)
        except Exception as cb_exc:  # noqa: BLE001
            log.debug("process_one_section progress_cb raised: %s", cb_exc)

    try:
        chunk_a_texts: List[str] = []
        chunk_b_texts: List[str] = []
        chunk_c_texts: List[str] = []
        chunk_a_models: List[str] = []
        chunk_b_models: List[str] = []
        chunk_c_models: List[str] = []
        any_fallback_chunks = False

        for ci, chunk in enumerate(chunks):
            chunk_label = f"{label}[{ci+1}/{n_chunks}]" if n_chunks > 1 else label
            chunk_terms = [t for t in section_terms if t and t in chunk]
            chunk_sfx = f" (chunk {ci+1}/{n_chunks})" if n_chunks > 1 else ""

            # Stage A — GPT-4o paraphrase (temperature 0.75 for diversity)
            _cb(1, f"Pass 1 of 3 — GPT-4o paraphrase{chunk_sfx}")
            a = _run_stage_with_timeout(
                primary="openai",
                system_prompt=STAGE_A_PARAPHRASE_PROMPT,
                user_text=chunk,
                protected_terms=chunk_terms,
                stage_label=f"A:{chunk_label}",
                timeout_seconds=stage_timeout,
                temperature=0.75,
            )
            chunk_a_texts.append(a["text"])
            chunk_a_models.append(a["model"])
            if a["fallback_used"]:
                any_fallback_chunks = True

            # Stage B — Gemini humanise / de-AI (temperature 0.65)
            _cb(2, f"Pass 2 of 3 — Gemini AI removal{chunk_sfx}")
            b = _run_stage_with_timeout(
                primary="gemini",
                system_prompt=STAGE_B_HUMANIZE_PROMPT,
                user_text=a["text"],
                protected_terms=chunk_terms,
                stage_label=f"B:{chunk_label}",
                timeout_seconds=stage_timeout,
                temperature=0.65,
            )
            chunk_b_texts.append(b["text"])
            chunk_b_models.append(b["model"])
            if b["fallback_used"]:
                any_fallback_chunks = True

            if light_mode:
                # Light intensity — skip the polish pass (similarity 10-15%)
                chunk_c_texts.append(b["text"])
                chunk_c_models.append("(skipped — light mode)")
            else:
                # Stage C — GPT-4o final polish (temperature 0.3 for precision)
                _cb(3, f"Pass 3 of 3 — GPT-4o polish{chunk_sfx}")
                c = _run_stage_with_timeout(
                    primary="openai",
                    system_prompt=STAGE_C_POLISH_PROMPT,
                    user_text=b["text"],
                    protected_terms=chunk_terms,
                    stage_label=f"C:{chunk_label}",
                    timeout_seconds=stage_timeout,
                    temperature=0.30,
                )
                chunk_c_texts.append(c["text"])
                chunk_c_models.append(c["model"])
                if c["fallback_used"]:
                    any_fallback_chunks = True

        # Reassemble chunks → single section output
        sep = "\n\n"
        a_combined = sep.join(chunk_a_texts)
        b_combined = sep.join(chunk_b_texts)
        c_combined = sep.join(chunk_c_texts)

        def _model_label(models: List[str]) -> str:
            unique = list(dict.fromkeys(models))  # deduplicate preserving order
            return unique[0] if len(unique) == 1 else f"{unique[0]} (multi-chunk)"

        a = {"text": a_combined, "model": _model_label(chunk_a_models),
             "fallback_used": any("fallback" in m for m in chunk_a_models)}
        b = {"text": b_combined, "model": _model_label(chunk_b_models),
             "fallback_used": any("fallback" in m for m in chunk_b_models)}
        c = {"text": c_combined, "model": _model_label(chunk_c_models),
             "fallback_used": any_fallback_chunks and not light_mode}
    except StageTimeoutError as exc:
        return {
            **base_entry,
            "status": "timed_out",
            "skipped": False,
            "error": str(exc),
            "elapsed_seconds": round(time.monotonic() - started, 1),
            "quality": {
                "key": "orange",
                "label": "Timed out",
                "hint": "This section did not finish within the per-section time budget. Use Retry to try again.",
            },
        }
    except ProviderQuotaExhausted:
        # Bubble up — the JobManager aborts the rest of the job because
        # later sections will hit the same wall and waste compute.
        raise
    except Exception as exc:  # noqa: BLE001
        log.exception("process_one_section %s failed", index)
        return {
            **base_entry,
            "status": "failed",
            "skipped": False,
            "error": sanitize_error_message(exc),
            "elapsed_seconds": round(time.monotonic() - started, 1),
            "quality": {
                "key": "orange",
                "label": "Failed",
                "hint": "An error prevented this section from being rewritten. Use Retry to try again.",
            },
        }

    edits = _approx_word_edits(body, c["text"])
    edit_pct = round(edits / max(1, _word_count) * 100)
    ai_residual = _score_ai_residual(c["text"])
    section_missing = [t for t in section_terms if t and t not in c["text"]]
    fallback_used = bool(a.get("fallback_used") or b.get("fallback_used") or c.get("fallback_used"))
    quality = _classify_section_quality(
        original=body,
        final=c["text"],
        edits=edits,
        missing_terms_count=len(section_missing),
        protected_terms_in_section=len(section_terms),
        fallback_used=fallback_used,
    )

    return {
        **base_entry,
        "status": "complete",
        "skipped": False,
        "stage_a_text": a["text"],
        "stage_b_text": b["text"],
        "stage_c_text": c["text"],
        "final_text": c["text"],
        "stage_models": {"a": a["model"], "b": b["model"], "c": c["model"]},
        "edits": edits,
        "edit_pct": edit_pct,
        "ai_residual": ai_residual,
        "protected_terms_in_section": len(section_terms),
        "missing_terms": section_missing,
        "fallback_used": fallback_used,
        "intensity": intensity,
        "quality": quality,
        "elapsed_seconds": round(time.monotonic() - started, 1),
    }


def _classify_section_quality(
    original: str,
    final: str,
    edits: int,
    missing_terms_count: int,
    protected_terms_in_section: int,
    fallback_used: bool,
) -> Dict[str, str]:
    """Assign a colour-coded quality bucket to a rewritten section.

    The four buckets follow the product spec:
      - green   "Well rewritten"           — substantial edits, clean
      - yellow  "Moderate changes"         — some edits made
      - orange  "Review recommended"       — few edits, or missing terms,
                                             or fallback provider was used
      - red     "Heavily technical"        — high protected-term density,
                                             paraphrase potential is naturally
                                             limited (mostly numbers / citations)

    Returned dict has ``key`` (machine), ``label`` (human), and ``hint``.
    """
    word_count = max(1, len(re.findall(r"\S+", original or "")))
    technical_density = protected_terms_in_section / word_count
    edit_ratio = edits / word_count

    # 1. Source is heavily technical → mark red regardless of edits, because
    #    the source naturally constrains how much can be rephrased. If the
    #    section ALSO has missing protected terms, surface that in the hint
    #    so the per-section card still warns about the preservation failure
    #    (red colour kept per product spec).
    if technical_density >= 0.08 or protected_terms_in_section >= 8:
        hint = "This section is dense with protected terms (numbers, drug names, citations) that cannot be paraphrased. Limited rewrite potential is expected."
        if missing_terms_count > 0:
            hint += f" ⚠ {missing_terms_count} protected term(s) did NOT survive the rewrite — restore them manually before submitting."
        return {"key": "red", "label": "Heavily technical", "hint": hint}
    # 2. Missing protected terms is a serious quality problem — flag for review.
    if missing_terms_count > 0:
        return {
            "key": "orange",
            "label": "Review recommended",
            "hint": f"{missing_terms_count} protected term(s) did not survive the rewrite. Please verify before accepting.",
        }
    # 3. Very small edit footprint OR fallback provider used → review.
    if edit_ratio < 0.10 or fallback_used:
        return {
            "key": "orange",
            "label": "Review recommended",
            "hint": "Few edits were made or a fallback provider was used. Compare the rewrite to the original carefully.",
        }
    # 4. Moderate edits.
    if edit_ratio < 0.25:
        return {
            "key": "yellow",
            "label": "Moderate changes",
            "hint": "The rewrite made some changes. Review for tone and accuracy.",
        }
    # 5. Substantial edits, clean run.
    return {
        "key": "green",
        "label": "Well rewritten",
        "hint": "Substantial paraphrasing with no preservation issues.",
    }


def rewrite_pipeline(
    sections: List[Dict[str, str]],
    *,
    protected_terms: Optional[List[str]] = None,
    progress_cb: Optional[Any] = None,
    cancel_event: Optional[Any] = None,
) -> Dict[str, Any]:
    """Run the 3-stage rewrite pipeline across a list of sections.

    Each ``sections`` item is ``{"label": str, "text": str}``. Sections
    whose label is References / Bibliography / Works Cited are skipped
    entirely (returned unchanged in the combined output, marked
    ``skipped: True``). Empty-text sections are dropped.

    The combined ``rewritten_text`` joins the per-section finals in input
    order with a blank line between them. Protected terms are passed to
    every stage AND verified against the combined final; any that didn't
    survive are reported in ``preserved_terms_missing``.
    """
    if not sections:
        raise ValueError("rewrite_pipeline requires at least one section")

    per_section: List[Dict[str, Any]] = []
    final_parts: List[str] = []
    total_changes = 0
    any_fallback = False
    protected_terms = protected_terms or []

    def _emit(event: Dict[str, Any]) -> None:
        if progress_cb is None:
            return
        try:
            progress_cb(event)
        except Exception as cb_exc:  # noqa: BLE001
            log.warning("progress_cb raised, continuing: %s", cb_exc)

    def _check_cancelled() -> None:
        if cancel_event is not None and cancel_event.is_set():
            raise PipelineCancelled("client disconnected, aborting pipeline")

    # Pre-compute the work plan so the client can render the progress bar
    # at the correct total before any stages run.
    plan_sections = []
    for i, sec in enumerate(sections):
        label_pre = (sec.get("label") or "").strip() or f"Section {i+1}"
        body_pre = (sec.get("text") or "").strip()
        if not body_pre:
            plan_sections.append({"index": i, "label": label_pre, "skipped": True, "skip_reason": "empty"})
        elif _is_references_label(label_pre):
            plan_sections.append({"index": i, "label": label_pre, "skipped": True, "skip_reason": "references"})
        else:
            plan_sections.append({"index": i, "label": label_pre, "skipped": False, "skip_reason": None})
    _emit({"type": "init", "total_sections": len(plan_sections), "sections": plan_sections})

    for i, sec in enumerate(sections):
        label = (sec.get("label") or "").strip() or "Section"
        body = (sec.get("text") or "").strip()
        if not body:
            entry = {
                "index": i,
                "label": label,
                "skipped": True,
                "skip_reason": "empty",
                "original": "",
                "final_text": "",
                "stage_a_text": "",
                "stage_b_text": "",
                "stage_c_text": "",
                "stage_models": {},
                "edits": 0,
                "quality": {"key": "gray", "label": "Empty", "hint": "No content to rewrite."},
                "missing_terms": [],
            }
            per_section.append(entry)
            _emit({"type": "section_done", "section": entry})
            continue

        if _is_references_label(label):
            entry = {
                "index": i,
                "label": label,
                "skipped": True,
                "skip_reason": "references",
                "original": body,
                "final_text": body,  # kept verbatim
                "stage_a_text": "",
                "stage_b_text": "",
                "stage_c_text": "",
                "stage_models": {},
                "edits": 0,
                "quality": {
                    "key": "gray",
                    "label": "Kept verbatim",
                    "hint": "References are never paraphrased.",
                },
                "missing_terms": [],
            }
            per_section.append(entry)
            final_parts.append(body)
            _emit({"type": "section_done", "section": entry})
            continue

        _check_cancelled()
        _emit({"type": "section_start", "index": i, "label": label})

        # Filter protected terms to those actually present in this section.
        section_terms = [t for t in protected_terms if t and t in body]

        # Stage A: GPT-4o paraphrase for originality
        a = _run_stage(
            primary="openai",
            system_prompt=STAGE_A_PARAPHRASE_PROMPT,
            user_text=body,
            protected_terms=section_terms,
            stage_label=f"A:{label}",
        )
        _emit({"type": "stage_done", "index": i, "stage": "a", "model": a["model"]})
        _check_cancelled()
        # Stage B: Gemini humanise
        b = _run_stage(
            primary="gemini",
            system_prompt=STAGE_B_HUMANIZE_PROMPT,
            user_text=a["text"],
            protected_terms=section_terms,
            stage_label=f"B:{label}",
        )
        _emit({"type": "stage_done", "index": i, "stage": "b", "model": b["model"]})
        _check_cancelled()
        # Stage C: GPT-4o quality polish
        c = _run_stage(
            primary="openai",
            system_prompt=STAGE_C_POLISH_PROMPT,
            user_text=b["text"],
            protected_terms=section_terms,
            stage_label=f"C:{label}",
        )
        _emit({"type": "stage_done", "index": i, "stage": "c", "model": c["model"]})

        section_fallback = a["fallback_used"] or b["fallback_used"] or c["fallback_used"]
        if section_fallback:
            any_fallback = True

        edits = _approx_word_edits(body, c["text"])
        # Per-section missing-terms check (pre combined verification below)
        section_missing = [t for t in section_terms if t and t not in c["text"]]
        quality = _classify_section_quality(
            original=body,
            final=c["text"],
            edits=edits,
            missing_terms_count=len(section_missing),
            protected_terms_in_section=len(section_terms),
            fallback_used=section_fallback,
        )

        entry = {
            "index": i,
            "label": label,
            "skipped": False,
            "original": body,
            "stage_a_text": a["text"],
            "stage_b_text": b["text"],
            "stage_c_text": c["text"],
            "final_text": c["text"],
            "stage_models": {"a": a["model"], "b": b["model"], "c": c["model"]},
            "edits": edits,
            "quality": quality,
            "missing_terms": section_missing,
        }
        per_section.append(entry)
        final_parts.append(c["text"])
        total_changes += edits
        _emit({"type": "section_done", "section": entry})

    final_combined = "\n\n".join(final_parts)
    if not final_combined.strip():
        # All sections were empty or only References (which we keep
        # verbatim but here even the verbatim text was empty). Treat as
        # a client input problem so the route returns 400, not 503.
        raise ValueError(
            "Pipeline produced no output: every supplied section was empty "
            "or contained only references. Please include at least one "
            "non-empty, non-References section."
        )

    missing = []
    for term in protected_terms:
        if term and term not in final_combined:
            missing.append(term)

    original_combined = "\n\n".join(
        (s.get("text") or "").strip() for s in sections if (s.get("text") or "").strip()
    )

    notes_bits = [f"3-stage pipeline across {sum(1 for s in per_section if not s['skipped'])} section(s)"]
    skipped_refs = [s["label"] for s in per_section if s.get("skip_reason") == "references"]
    if skipped_refs:
        notes_bits.append(f"References kept verbatim: {', '.join(skipped_refs)}")
    if any_fallback:
        notes_bits.append("one or more stages used the fallback provider")

    final_result = {
        "original_text": original_combined,
        "rewritten_text": final_combined,
        "changes_made": total_changes,
        "notes": ". ".join(notes_bits) + ".",
        "model_used": "pipeline (gpt-4o → gemini-2.5-flash → gpt-4o)" + (" + fallbacks" if any_fallback else ""),
        "protected_terms_count": len(protected_terms),
        "preserved_terms_missing": missing[:50],
        "pipeline": {
            "stages": [
                {"key": "a", "name": "Paraphrase for originality", "primary": "gpt-4o"},
                {"key": "b", "name": "De-AI / humanise", "primary": "gemini-2.5-flash"},
                {"key": "c", "name": "Quality polish", "primary": "gpt-4o"},
            ],
            "any_fallback": any_fallback,
            "sections": per_section,
        },
    }
    _emit({"type": "complete", "result": final_result})
    return final_result


# ---------------------------------------------------------------------------
# File-text extraction
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Upload-extraction errors
# ---------------------------------------------------------------------------
# These are caught at the route layer and translated into HTTP responses
# with friendly user-facing messages. Keep the messages free of any API keys
# or internal paths — the route layer also calls sanitize_error_message() on
# anything that flows back to the client.

MAX_PAGES_PDF = 200  # Cost/abuse protection — see /api/plagiarism docstring.


class UploadExtractionError(Exception):
    """Base class for clean, user-facing upload errors."""

    http_status: int = 400


class UnsupportedFileError(UploadExtractionError):
    http_status = 415


class PasswordProtectedError(UploadExtractionError):
    http_status = 400


class ImageOnlyPdfError(UploadExtractionError):
    http_status = 422


class DocumentTooLargeError(UploadExtractionError):
    http_status = 413


class CorruptedFileError(UploadExtractionError):
    http_status = 400


# Patterns for stripping anything that looks like a credential before an
# error message is returned to the browser. Belt-and-braces — provider
# error strings should not contain these in the first place.
_API_KEY_PATTERNS = [
    re.compile(r"sk-[A-Za-z0-9_\-]{16,}"),
    re.compile(r"AIza[0-9A-Za-z_\-]{16,}"),
    re.compile(r"Bearer\s+[A-Za-z0-9_\-\.]+", re.IGNORECASE),
    re.compile(r"api[_-]?key['\"\s:=]+[A-Za-z0-9_\-]{16,}", re.IGNORECASE),
    re.compile(r"x-api-key[:\s=]+[A-Za-z0-9_\-]{16,}", re.IGNORECASE),
]


def sanitize_error_message(msg: str | Exception) -> str:
    """Strip anything that looks like an API key from an error string.

    Defence in depth — provider SDKs should not embed keys in their error
    text, but this guarantees nothing leaks even if they ever did.
    """
    text = str(msg)
    for pat in _API_KEY_PATTERNS:
        text = pat.sub("[redacted]", text)
    return text


def extract_text_from_upload(filename: str, content: bytes) -> str:
    """Pull plain text from an uploaded PDF / DOCX / TXT file.

    Raises a subclass of :class:`UploadExtractionError` with a user-safe
    message for each known failure mode. Files larger than the byte cap
    are rejected at the route layer; this function additionally enforces
    a page cap for PDFs (``MAX_PAGES_PDF``).
    """
    name = (filename or "").lower()

    if name.endswith(".txt") or name.endswith(".md"):
        try:
            return content.decode("utf-8", errors="replace")
        except Exception:
            return content.decode("latin-1", errors="replace")

    if name.endswith(".pdf"):
        from io import BytesIO
        try:
            from pypdf import PdfReader
            from pypdf.errors import PdfReadError, FileNotDecryptedError
        except ImportError:  # pragma: no cover
            from pypdf import PdfReader  # type: ignore
            PdfReadError = Exception  # type: ignore
            FileNotDecryptedError = Exception  # type: ignore

        try:
            reader = PdfReader(BytesIO(content))
        except PdfReadError as exc:
            raise CorruptedFileError(
                "This PDF file looks corrupted or is not a valid PDF. Please re-export it and try again."
            ) from exc
        except Exception as exc:
            raise CorruptedFileError(
                "We could not open this PDF file. Please make sure it is a valid PDF and try again."
            ) from exc

        # Password-protected PDF: try empty password (some PDFs are
        # encrypted but readable with no password); if that fails, ask
        # the user to remove the password.
        if getattr(reader, "is_encrypted", False):
            decrypted = False
            try:
                if reader.decrypt("") in (1, 2):  # type: ignore[arg-type]
                    decrypted = True
            except Exception:
                decrypted = False
            if not decrypted:
                raise PasswordProtectedError(
                    "This PDF is password protected. Please remove the password in your PDF reader (File → Export / Print to PDF without security), then upload again."
                )

        try:
            page_count = len(reader.pages)
        except Exception:
            page_count = 0

        if page_count > MAX_PAGES_PDF:
            raise DocumentTooLargeError(
                f"This document has {page_count} pages, which exceeds the {MAX_PAGES_PDF}-page limit. Please split it into smaller documents and upload each part separately."
            )

        parts: list[str] = []
        for page in reader.pages:
            try:
                parts.append(page.extract_text() or "")
            except FileNotDecryptedError as exc:
                raise PasswordProtectedError(
                    "This PDF is password protected. Please remove the password and upload again."
                ) from exc
            except Exception:
                continue

        text = "\n\n".join(p for p in parts if p.strip())

        # Image-only / scanned PDF: pages exist but no extractable text.
        # We don't run OCR — surface a clear, actionable error.
        if not text.strip() and page_count > 0:
            raise ImageOnlyPdfError(
                "This PDF appears to contain only scanned images, not selectable text. Please run it through OCR (e.g. Adobe Acrobat → Recognize Text, or an online OCR tool) and upload the resulting searchable PDF."
            )

        return text

    if name.endswith(".docx"):
        from io import BytesIO
        try:
            import docx  # python-docx
            from docx.opc.exceptions import PackageNotFoundError
        except ImportError:  # pragma: no cover
            import docx  # type: ignore
            PackageNotFoundError = Exception  # type: ignore

        try:
            doc = docx.Document(BytesIO(content))
        except PackageNotFoundError as exc:
            # Old .doc, password-protected .docx, or unrelated file with
            # a .docx extension all raise PackageNotFoundError. Give a
            # clear next step for each likely cause.
            raise CorruptedFileError(
                "We could not open this Word document. If it is password protected, remove the password (File → Info → Protect Document → Encrypt with Password → delete password). If it is an old .doc file, save it as .docx in Word first."
            ) from exc
        except Exception as exc:
            raise CorruptedFileError(
                "We could not read this Word document. Please re-save it as .docx in Word and try again."
            ) from exc

        return "\n".join(p.text for p in doc.paragraphs if p.text)

    raise UnsupportedFileError(
        "Unsupported file type. Please upload a .pdf, .docx, .txt or .md file."
    )
