"""Proposal Writing Module — Step 5 (References) API.

* ``POST /api/references/extract``      — multi-file upload → extracted refs
* ``POST /api/references/generate``     — JSON: topic/count → AI refs (flagged)
* ``POST /api/references/validate-doi`` — JSON: {doi} → Crossref check
* ``POST /api/references/format``       — JSON: refs + style → formatted strings
* ``POST /api/references/dedupe``       — JSON: refs → indexes flagged as dupes
"""

from __future__ import annotations
from fastapi import Request

import asyncio
from typing import Any, Dict, List

from fastapi import APIRouter, File, Form, HTTPException, UploadFile

from app.services import (
    citation_formatter,
    doi_validator,
    plagiarism_analyzer,
    reference_extractor,
    reference_generator,
)

router = APIRouter(prefix="/references", tags=["references"])

MAX_FILE_BYTES = 100 * 1024 * 1024
MAX_FILES_PER_BATCH = 10
MAX_TOTAL_BYTES = 200 * 1024 * 1024


async def _read_with_cap(file: UploadFile, cap: int) -> bytes:
    chunks: List[bytes] = []
    total = 0
    while True:
        chunk = await file.read(64 * 1024)
        if not chunk: break
        total += len(chunk)
        if total > cap:
            raise HTTPException(
                status_code=413,
                detail=f"'{file.filename or 'upload'}' exceeds {cap // (1024 * 1024)} MB.",
            )
        chunks.append(chunk)
    return b"".join(chunks)


@router.post("/extract")
async def extract_refs(files: List[UploadFile] = File(...)) -> Dict[str, Any]:
    if not files:
        raise HTTPException(400, "Upload at least one file.")
    if len(files) > MAX_FILES_PER_BATCH:
        raise HTTPException(400, f"Too many files (max {MAX_FILES_PER_BATCH}).")

    file_results: List[Dict[str, Any]] = []
    all_refs: List[Dict[str, Any]] = []
    running = 0

    for upload in files:
        fname = upload.filename or "(unnamed)"
        try:
            raw = await _read_with_cap(upload, MAX_FILE_BYTES)
        except HTTPException as exc:
            file_results.append({"name": fname, "ok": False, "error": exc.detail, "count": 0})
            continue
        running += len(raw)
        if running > MAX_TOTAL_BYTES:
            file_results.append({"name": fname, "ok": False, "error": "Combined size cap exceeded.", "count": 0})
            continue
        try:
            refs = reference_extractor.extract_references_from_upload(fname, raw)
        except plagiarism_analyzer.ProviderQuotaExhausted:
            raise HTTPException(503, "AI service is temporarily over its quota. Please try again later.")
        except Exception as exc:
            from app.services import outline_extractor as _oe
            if isinstance(exc, _oe.UploadExtractionError):
                file_results.append({"name": fname, "ok": False, "error": str(exc), "count": 0})
                continue
            msg = plagiarism_analyzer.sanitize_error_message(str(exc))
            file_results.append({"name": fname, "ok": False, "error": msg, "count": 0})
            continue

        file_results.append({"name": fname, "ok": True, "count": len(refs)})
        all_refs.extend(refs)

    duplicates = doi_validator.find_duplicates(all_refs)
    return {
        "references": all_refs,
        "files": file_results,
        "total_extracted": len(all_refs),
        "duplicates": duplicates,
    }


@router.post("/generate")
async def generate_refs(request: Request, payload: Dict[str, Any]) -> Dict[str, Any]:
    from app.services.external_ai_consent import require_external_ai_consent
    require_external_ai_consent(request)
    topic = str(payload.get("topic") or "").strip()
    if not topic:
        raise HTTPException(400, "`topic` is required.")
    count = int(payload.get("count") or 15)
    recency = int(payload.get("recency_years") or reference_generator.DEFAULT_RECENCY_YEARS)
    journals = payload.get("journals")
    if journals is not None and not isinstance(journals, list):
        raise HTTPException(400, "`journals` must be a list of strings.")

    try:
        refs = reference_generator.generate_plausible_references(
            topic=topic, count=count, recency_years=recency, journals=journals,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    except plagiarism_analyzer.ProviderQuotaExhausted:
        raise HTTPException(503, "AI service is temporarily over its quota. Please try again later.")
    except Exception as exc:
        msg = plagiarism_analyzer.sanitize_error_message(str(exc))
        raise HTTPException(502, f"Generation failed: {msg}")

    return {
        "references": refs,
        "count": len(refs),
        "warning": (
            "These references were generated by AI as starting suggestions. "
            "They may not exist exactly as written — please verify each one "
            "in PubMed or Google Scholar before citing."
        ),
    }


@router.post("/validate-doi")
async def validate_doi_endpoint(payload: Dict[str, Any]) -> Dict[str, Any]:
    doi = str(payload.get("doi") or "").strip()
    if not doi:
        raise HTTPException(400, "`doi` is required.")
    # Run the blocking urllib call in a worker thread so we don't stall the
    # FastAPI event loop while waiting on Crossref (up to 5 s).
    return await asyncio.to_thread(doi_validator.validate_doi, doi)


@router.post("/format")
async def format_refs(payload: Dict[str, Any]) -> Dict[str, Any]:
    refs = payload.get("references")
    style = str(payload.get("style") or citation_formatter.DEFAULT_STYLE)
    if not isinstance(refs, list):
        raise HTTPException(400, "`references` must be a list.")
    formatted = citation_formatter.format_all([r if isinstance(r, dict) else {} for r in refs], style)
    return {"style": style, "formatted": formatted, "count": len(formatted)}


@router.post("/dedupe")
async def dedupe_refs(payload: Dict[str, Any]) -> Dict[str, Any]:
    refs = payload.get("references")
    if not isinstance(refs, list):
        raise HTTPException(400, "`references` must be a list.")
    return {"duplicates": doi_validator.find_duplicates(refs)}
