kind = "web"
previewPath = "/"
title = "Novus"
version = "1.0.0"
id = "artifacts/novus"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22142

[services.development]
run = "pnpm --filter @workspace/novus run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/novus", "run", "build" ]
publicDir = "artifacts/novus/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22142"
BASE_PATH = "/"
